### ISSUE TITLE
Makes notes visible

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#255]
Could you please make the _notes_ field publicly visible in the summary details view? We are using it, for example, to inform people when authors weren't contactable and we therefore couldn't ask for their approval.

**Comment by paluchas** [comment]
Resolved with #268

**Comment by IAlferink** [comment]
@paluchas @yf508 This issue has been closed and was moved to production a few months ago. However, the issue is not resolved. The notes field is still invisible. Can you please fix this. We really need this done.
