### ISSUE TITLE
Upload form: summary view after submitting

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#58]
I completed the form and then clicked save. Saving the summary brings up the summary detailed view page. The icon displayed with the summary was the wrong size (see below). 

![image](https://user-images.githubusercontent.com/36402489/36722750-510fd5be-1ba6-11e8-9b75-46b2373fcaa8.png)

However, when I access the summary detailed view page through the Search and download interface, the icon is the correct size. This seems to only be a problem for the summary page when it is presented to the uplaoder immediately after saving the summary.

**Comment by yf508** [comment]
fixed and on demo site.

**Comment by paluchas** [comment]
I did notice this behaviour too. I need to do more testing whether this bug remains once thumbnails generation and file characterisation Hyrax's features are configured.

**Comment by RKasprowicz** [comment]
@paluchas I haven't noticed this issue again recently.
