### ISSUE TITLE
Search results page: Terms under for some metadata fields are not displaying correctly

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#68]
1. Search terms under the "Topic" field are incorrectly showing journal names.
![image](https://user-images.githubusercontent.com/36402489/37090510-92e21f22-21fc-11e8-895b-b8631c6d61b9.png)

2. Some of the terms displaying under "Participant Type" are incorrect:
(the Young learners / adolescent learners / adult learners should display under "Age of learners" (in line with the new checkboxes implemented - see issues #45 #61 - see also the [Updated_OASIS Search terms](https://docs.google.com/spreadsheets/d/1rGBsH857eKLQgozQR_pAzROjZtFl-e2Jd3jcwojekSo/edit?usp=sharing) sheet for the correct list of terms to appear under "Participant type" vs. "Age of learners"
![image](https://user-images.githubusercontent.com/36402489/37090544-b12676f4-21fc-11e8-9c65-50844a19829d.png)

**Comment by RKasprowicz** [comment]
In addition, no information is displaying for "Age of learners" 

![image](https://user-images.githubusercontent.com/36402489/37160150-7b513b0e-22e7-11e8-98cd-b05ad09b4495.png)

**Comment by yf508** [comment]
1) has been fixed. Will be available on next update on demo site.
Regarding 2). I've updated the participant types. You may want to edit the record to see if they are displayed correctly.

**Comment by RKasprowicz** [comment]
@yf508 2. does not seem to be resolved yet. I am still seeing the same display as above (with young learners etc appearing under "Participant type" in the upload form, search facet on search results page, and summary detailed view page.

**Comment by paluchas** [comment]
@RKasprowicz You can test this now. I have deployed new code to demo site. It worked on my local dev.

**Comment by yf508** [comment]
@RKasprowicz 2) appears not fixed because the data was entered with the old participant entries, e.g 'Young learners' was in participant list but now moved to 'age of learners'.  It won't fix itself until a manual edit.

Pls could you re-edit the data and see if it shows correctly? thx

**Comment by RKasprowicz** [comment]
@yf508 1. and 2. above are fixed. But there is still no information displaying for age of learners. 
I have manually edited the summary below, and selected "young learners" from the drop-down list under "age of learners" in the upload form. However, on the search results no information is displaying for age see (a) below, and on the detailed view page the old, incorrect age information is showing (see (b) below).

(a)
![image](https://user-images.githubusercontent.com/36402489/37211096-bedaea80-23a2-11e8-9fe2-93573229d84e.png)

(b)
![image](https://user-images.githubusercontent.com/36402489/37211049-9bd13e5e-23a2-11e8-9d07-d2a171d9779a.png)

**Comment by paluchas** [comment]
@RKasprowicz Age of participants should display correctly now, part of #95.

**Comment by RKasprowicz** [comment]
@paluchas Yes the age of learners categories are now displaying correctly.
